% simple convert stuff

imwrite(uint8(ace), 'ace.png')    
imwrite(uint8(club), 'club.png')
imwrite(uint8(diamond), 'diamond.png')
imwrite(uint8(eight), 'eight.png')
imwrite(uint8(five), 'five.png')
imwrite(uint8(four), 'four.png')
imwrite(uint8(heart), 'heart.png')
imwrite(uint8(jack), 'jack.png')
imwrite(uint8(king), 'king.png')
imwrite(uint8(nine), 'nine.png')
imwrite(uint8(queen), 'queen.png')
imwrite(uint8(seven), 'seven.png')
imwrite(uint8(six), 'six.png')
imwrite(uint8(spade), 'spade.png')
imwrite(uint8(ten), 'ten.png')
imwrite(uint8(three), 'three.png')
imwrite(uint8(two), 'two.png')